#!/bin/bash

set -ex -o pipefail

# Test "myjoin" using a small data set.

data_dir=${DATA_DIR:-/localtmp/efficient24}
data_files="${data_dir}/a.csv ${data_dir}/b.csv ${data_dir}/c.csv ${data_dir}/d.csv"
data_expected=${data_dir}/abcd.csv

python3 ./src/main.py $data_files | sort | diff - $data_expected
