#!/bin/bash

set -ex -o pipefail

# Test "myjoin" using a large data set.

data_dir=${DATA_DIR:-/localtmp/efficient24}
data_files="${data_dir}/f1.csv ${data_dir}/f2.csv ${data_dir}/f3.csv ${data_dir}/f4.csv"
data_expected=${data_dir}/output.csv

./build/myjoin $data_files | sort | diff - $data_expected
